---
title: "Plot marker genes"
---
  
```{r load_modules, echo=FALSE, include=FALSE}
library(scran)
library(ggpubr)
```

# Define settings

Define I/O
```{r define_io, echo=FALSE}
source("/Users/ricard/gastrulation10x/settings.R")

io$outdir <- paste0(io$basedir,"/results/marker_genes/pdf")
```

Define options
```{r}
opts$celltypes <- c(
	"Epiblast",
	"Primitive Streak",
	"Caudal epiblast",
	"PGC",
	"Anterior Primitive Streak",
	"Notochord",
	"Def. endoderm",
	"Gut",
	"Nascent mesoderm",
	"Mixed mesoderm",
	"Intermediate mesoderm",
	"Caudal Mesoderm",
	"Paraxial mesoderm",
	"Somitic mesoderm",
	"Pharyngeal mesoderm",
	"Cardiomyocytes",
	"Allantois",
	"ExE mesoderm",
	"Mesenchyme",
	"Haematoendothelial progenitors",
	"Endothelium",
	"Blood progenitors 1",
	"Blood progenitors 2",
	"Erythroid1",
	"Erythroid2",
	"Erythroid3",
	"NMP",
	"Rostral neurectoderm",
	"Caudal neurectoderm",
	"Neural crest",
	"Forebrain_Midbrain_Hindbrain",
	"Spinal cord",
	"Surface ectoderm",
	"Visceral endoderm",
	"ExE endoderm",
	"ExE ectoderm",
	"Parietal endoderm"
)
```

Update sample metadata
```{r}
sample_metadata <- sample_metadata[celltype%in%opts$celltypes]
```

# Load data 

Load RNA expression data
```{r load_data, echo=FALSE}
# sce <- readRDS(io$rna.sce)[,sample_metadata$cell]
# sce$group <- sample_metadata$celltype
```

Load pre-computed marker genes
```{r}
marker_genes.dt <- fread(io$marker_genes)
marker.genes <- unique(marker_genes.dt$gene)
```

Load average expression per cluster and gene
```{r}
avgexpr.dt <- fread(io$average_expression_per_celltype) %>%
  setnames("mean_expr","expr")
```

# Plot

Plot top N genes with highest expression levels
```{r}
opts$top_genes <- 50

for (i in unique(sample_metadata$celltype)) {

  dt.filt <- avgexpr.dt[group==i] %>%
    setorder(-expr) %>% head(opts$top_genes) %>%
    .[,gene:=factor(gene,levels=rev(gene))]

  p <- ggbarplot(dt.filt, x="gene", y="expr", fill="#3CB54E", color="black") +
    coord_flip() +
    labs(x="RNA expression",y="") +
    theme(
      axis.text.y = element_text(size=rel(0.8))
    )

  pdf(sprintf("%s/%s_top_genes.pdf",io$outdir,i), width = 5, height = 8)
  print(p)
  dev.off()
}
```

Plot a heatmap of the average expression of marker genes per cluster
```{r}
opts$scale <- TRUE

for (i in unique(sample_metadata$celltype)) {

  genes <- marker_genes.dt[group==i,gene]
  
  to.plot <- avgexpr.dt[gene%in%genes] %>% 
    .[,gene:=factor(gene,levels=genes)]
    
   # Scale expression by gene
  if (isTRUE(opts$scale)) {
    to.plot %>% .[,expr:=expr/max(expr),by="gene"]
  }
  
  p <- ggplot(to.plot, aes_string(x="group", y="gene", fill="expr")) +
    geom_tile() +
    labs(x="",y="") +
    theme_classic() +
  	scale_fill_gradient(low = "white", high = "red") +
    theme(
      legend.position = "none",
      axis.text.y = element_text(color="black"),
      axis.text.x = element_text(color="black", angle=90, hjust=1, size=rel(1.0), vjust=0.5)
    )
  
  pdf(sprintf("%s/%s_heatmap_marker_genes.pdf",io$outdir,i), width = 6, height = 8)
  print(p)
  dev.off()
}
```

