---
title: "Dimensionality reduction exploration"
---
  
```{r load_modules, echo=FALSE, include=FALSE}
library(SingleCellExperiment)
library(scran)
library(scater)
```

# Define settings

Define I/O
```{r define_io, echo=FALSE}
source("/Users/ricard/gastrulation10x/settings.R")
io$outdir <- paste0(io$basedir,"/results/dimensionality_reduction/test")
```

Define options
```{r}
opts$stages <- c(
  # "E6.5",
  # "E6.75",
  # "E7.0",
  # "E7.25",
  "E7.5"
  # "E7.75",
  # "E8.0",
  # "E8.25",
  # "E8.5"
  # "mixed_gastrulation"
)

opts$celltypes = c(
	# "Epiblast",
	# "Primitive_Streak"
	# "Caudal_epiblast",
	# "PGC",
	# "Anterior_Primitive_Streak",
	# "Notochord",
	"Def._endoderm",
	"Gut"
	# "Nascent_mesoderm",
	# "Mixed_mesoderm",
	# "Intermediate_mesoderm",
	# "Caudal_Mesoderm",
	# "Paraxial_mesoderm",
	# "Somitic_mesoderm",
	# "Pharyngeal_mesoderm",
	# "Cardiomyocytes",
	# "Allantois",
	# "ExE_mesoderm",
	# "Mesenchyme",
	# "Haematoendothelial_progenitors",
	# "Endothelium",
	# "Blood_progenitors_1",
	# "Blood_progenitors_2",
	# "Erythroid1",
	# "Erythroid2",
	# "Erythroid3",
	# "NMP",
	# "Rostral_neurectoderm"
	# "Caudal_neurectoderm",
	# "Neural_crest",
	# "Forebrain_Midbrain_Hindbrain",
	# "Spinal_cord",
	# "Surface_ectoderm",
	# "Visceral_endoderm",
	# "ExE_endoderm",
	# "ExE_ectoderm",
	# "Parietal_endoderm"
)
opts$remove.ExE.celltypes <- TRUE
opts$batch_correction <- FALSE
```

Update sample metadata
```{r load_metadata, echo=FALSE}
sample_metadata <- sample_metadata %>%
  .[stage%in%opts$stages & celltype%in%opts$celltypes] %>%
  droplevels

if (opts$remove.ExE.celltypes) {
  sample_metadata <- sample_metadata %>%
    .[!celltype%in%c("Visceral_endoderm","ExE_endoderm","ExE_ectoderm","Parietal_endoderm")]
}
table(sample_metadata$sample)
```

# Load data

Load RNA expression data as SingleCellExperiment object
```{r load_data, echo=FALSE}
sce <- load_SingleCellExperiment(io$sce, 
  cells = sample_metadata$cell, 
  remove_non_expressed_genes = TRUE,
  normalise = TRUE
)
dim(sce)
```

Add sample metadata to the colData of the SingleCellExperiment
```{r}
colData(sce) <- sample_metadata %>% as.data.frame %>% tibble::column_to_rownames("cell") %>%
  .[colnames(sce),] %>% DataFrame()
```

Change gene names from ENSEMBL to symbols
```{r}
gene_metadata <- fread(io$gene_metadata) %>% .[,c("ens_id","symbol")] %>%
  .[symbol!="" & ens_id%in%rownames(sce)]

sce <- sce[rownames(sce)%in%gene_metadata$ens_id,]
foo <- gene_metadata$symbol; names(foo) <- gene_metadata$ens_id
new.names <- foo[rownames(sce)]

# Sanity cehcks
stopifnot(sum(is.na(new.names))==0)
stopifnot(sum(duplicated(new.names))==0)

# Set names
rownames(sce) <- new.names
```

# Parse data

Select HVG
```{r}
decomp <- modelGeneVar(sce)
decomp <- decomp[decomp$mean > 0.01,]
hvgs <- rownames(decomp)[decomp$p.value <= 0.01]

# Subset SingleCellExperiment
sce_filt <- sce[hvgs,]
dim(sce_filt)
```

# PCA

Run PCA
```{r}
set.seed(42)
sce_filt <- runPCA(sce_filt, ncomponents = 5, ntop=nrow(sce_filt))
reducedDim(sce, "PCA") <- reducedDim(sce_filt, "PCA") 
```

```{r}
# cor(colMeans(assay(sce,"logcounts")), reducedDim(sce_filt, "PCA"))
```

Plot PCA
```{r}
p <- plotPCA(sce_filt, colour_by="stage", ncomponents = c(1,2)) +
  scale_colour_manual(values=opts$stage.colors)

# pdf(sprintf("%s/nmp_vs_caudalepi_pca_by_stage.pdf",io$outdir), width=6, height=4)
print(p)
# dev.off()
```

```{r}
p <- plotPCA(sce_filt, colour_by="celltype", ncomponents = c(1,2)) +
  scale_colour_manual(values=opts$celltype.colors)

# pdf(sprintf("%s/nmp_vs_caudalepi_pca_by_celltype.pdf",io$outdir), width=6, height=4)
print(p)
# dev.off()
```

# Batch correction
```{r}
if (opts$batch_correction) {
  if (length(unique(sce_filt$sample))>1) {
    library(batchelor)
    pca <- multiBatchPCA(sce_filt, batch=sce_filt$sample)
    pca.corrected <- reducedMNN(pca)$corrected
    colnames(pca.corrected) <- paste0("PC",1:ncol(pca.corrected))
    reducedDim(sce_filt, "PCA") <- pca.corrected
  }
}
```

# UMAP

Run UMAP
```{r}
set.seed(42)
# sce_filt <- runUMAP(sce_filt, dimred="PCA")
sce_filt <- runUMAP(sce_filt, dimred="PCA", n_neighbors = 35, min_dist = 0.45)
reducedDim(sce, "UMAP") <- reducedDim(sce_filt, "UMAP") 
```


Plot UMAP

```{r}
to.plot <- reducedDim(sce_filt,"UMAP") %>% as.data.table %>% 
  .[,cell:=colnames(sce_filt)] %>%
    merge(sample_metadata, by="cell")
```

```{r}
p <- ggplot(to.plot, aes(x=V1, y=V2, fill=celltype)) +
  geom_point(size=1.5, shape=21, stroke=0.2) +
  scale_fill_manual(values=opts$celltype.colors) +
  theme_classic() +
  theme(
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    legend.position="none",
    legend.title=element_blank()
  )

# pdf(paste0(io$outdir,"/rna_umap.pdf"), width=5, height=3, useDingbats = F)
print(p)
# dev.off()
```

Plot marker genes
```{r}
io$diff.dir <- paste0(io$basedir,"/results/differential/celltypes/all_stages")
file <- sprintf("%s/Caudal_epiblast_vs_NMP.txt.gz", io$diff.dir)
diff.dt <- fread(file) %>% .[sig==T & abs(logFC)>1.5]
```

```{r}
genes.to.plot <- diff.dt$gene[diff.dt$gene%in%rownames(sce)] 

for (i in genes.to.plot) {
  
  p <- plotPCA(sce, colour_by=i, ncomponents = c(1,2))
  
  pdf(sprintf("%s/%s_nmp_vs_caudalepi.pdf",io$outdir,i), width=6, height=4)
  print(p)
  dev.off()
}
```

