
```{r}
opts$factors.width <- 8
opts$factors.height <- 4
```

<!-- Factor 1  -->

Plot factors
```{r}
p <- plot_factors(
  model,
  factors = c(10),
  group_by = "group",
  color_by = sample_metadata_filt$lineage10x_2,
  dodge=T, dot_size=1, legend = F, rasterize = T
)
p <- p + scale_color_manual(values=opts$colors)
p <- p + theme(
  strip.text = element_text(size=rel(1.3), color="black"),
  strip.background = element_blank(),
)

print(p)

# pdf(paste0(io$pdfdir,"/Factor1_values.pdf"), width=opts$factors.width, height=opts$factors.height, useDingbats = F)
# print(p)
# dev.off()
```

Plot weights
```{r}
# p <- plot_weights(model, 
#   view = "RNA", 
#   factor = 1, 
#   nfeatures = 10,
#   text_size = 5,
#   scale=T, abs=F
# )

p <- plot_top_weights(model, 
  view = "RNA", 
  factor = 1, 
  nfeatures = 10,
  scale=T, abs=T, 
)

pdf(paste0(io$pdfdir,"/Factor1_loadings.pdf"), width=3.5, height=3, useDingbats = F)
print(p)
dev.off()
```

Plot factor coloured by gene expression
```{r}
genes <- c("Ttr","Apom","Apoa1","Amn")
# genes <- c("Ttr")

for (i in genes) {
  
  p <- plot_factors(model,
    factors = 1,
    group_by = "group",
    color_by = i,
    rasterize = F,
    legend=F
  )
  # p <- p + scale_colour_gradientn(colours = terrain.colors(10))
  p <- p + theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks.y = element_blank(),
    strip.text = element_blank(),
    strip.background = element_blank()
  )
  # print(p)
  
  pdf(sprintf("%s/Factor1_%s.pdf",io$pdfdir,i), width=4, height=3, useDingbats = F)
  print(p)
  dev.off()
}
```










<!-- Factor 2  -->

Plot factors
```{r}
p <- plot_factors(
  model,
  factors = c(2),
  group_by = "group",
  color_by = sample_metadata_filt$lineage10x_2,
  dodge=T, dot_size=1, legend = F, rasterize = T
)
p <- p + scale_color_manual(values=opts$colors)
p <- p + theme(
  strip.text = element_text(size=rel(1.3), color="black"),
  strip.background = element_blank(),
)
# print(p)

pdf(paste0(io$pdfdir,"/Factor2_values.pdf"), width=opts$factor.width, height=opts$factor.height, useDingbats = F)
print(p)
dev.off()
```

Plot weights
```{r}
# p <- plot_weights(model, 
#   view = "RNA", 
#   factor = 2, 
#   nfeatures = 10,
#   text_size = 5,
#   scale=T, abs=F
# )

p <- plot_top_weights(model, 
  view = "RNA", 
  factor = 2, 
  nfeatures = 10,
  scale=T, abs=T
)
# print(p)

pdf(paste0(io$pdfdir,"/Factor2_loadings.pdf"), width=3.5, height=3, useDingbats = F)
print(p)
dev.off()
```

Plot factor coloured by gene expression
```{r}
# genes <- c("Ttr","Apom","Apoa1","Amn")
genes <- c("Rhox5","Elf5","Bex3","Gjb3")

for (i in genes) {
  
  p <- plot_factors(model,
    factors = 2,
    group_by = "group",
    color_by = i,
    rasterize = F,
    legend=F
  )
  # p <- p + scale_colour_gradientn(colours = terrain.colors(10))
  p <- p + theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks.y = element_blank(),
    strip.text = element_blank(),
    strip.background = element_blank()
  )
  # print(p)
  
  pdf(sprintf("%s/Factor2_%s.pdf",io$pdfdir,i), width=4, height=3, useDingbats = F)
  print(p)
  dev.off()
}
```





<!-- Factor 3  -->

Plot factors
```{r}
p <- plot_factors(
  model,
  factors = c(3),
  group_by = "group",
  color_by = sample_metadata_filt$lineage10x_2,
  dodge=T, dot_size=1, legend = F, rasterize = T
)
p <- p + scale_color_manual(values=opts$colors)
p <- p + theme(
  strip.text = element_text(size=rel(1.3), color="black"),
  strip.background = element_blank(),
)

print(p)

# pdf(paste0(io$pdfdir,"/Factor3_values.pdf"), width=10, height=4, useDingbats = F)
# print(p)
# dev.off()
```

Plot weights
```{r}
p <- plot_top_weights(model, 
  view = "RNA", 
  factor = 3, 
  nfeatures = 10,
  scale=T, abs=T
)
print(p)

# pdf(paste0(io$pdfdir,"/Factor3_loadings.pdf"), width=7, height=5, useDingbats = F)
# print(p)
# dev.off()
```

Plot factor coloured by gene expression
```{r}
# genes <- c("Ttr","Apom","Apoa1","Amn")
genes <- c("Hspa8","Atp5b")

for (i in genes) {
  p <- plot_factors(model,
    factors = 3,
    group_by = "group",
    color_by = i,
    rasterize = F
  )
  # p <- p + scale_colour_gradientn(colours = terrain.colors(10))
  p <- p + theme(
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    strip.text = element_text(size=rel(1.3), color="black"),
    strip.background = element_blank(),
  )
  
  print(p)
  
  # pdf(paste0(io$pdfdir,"/Factor3_%s.pdf",i), width=10, height=4, useDingbats = F)
  # print(p)
  # dev.off()
}
```



<!-- Factor 4  -->

Plot factor values
```{r}
p <- plot_factors(
  model,
  factors = c(4),
  group_by = "group",
  color_by = sample_metadata_filt$lineage10x_2,
  dodge=T, dot_size=1, legend = F, rasterize = T
)
p <- p + scale_color_manual(values=opts$colors)
p <- p + theme(
  strip.text = element_text(size=rel(1.3), color="black"),
  strip.background = element_blank(),
)
# print(p)

pdf(paste0(io$pdfdir,"/Factor4_values.pdf"), width=opts$factors.width, height=opts$factors.height, useDingbats = F)
print(p)
dev.off()
```

Plot weights
```{r}
# p <- plot_weights(model, 
#   view = "RNA", 
#   factor = 1, 
#   nfeatures = 10,
#   text_size = 5,
#   scale=T, abs=F
# )

p <- plot_top_weights(model, 
  view = "RNA", 
  factor = 4, 
  nfeatures = 10,
  scale=T, abs=T, 
)

pdf(paste0(io$pdfdir,"/Factor4_loadings.pdf"), width=3.5, height=3, useDingbats = F)
print(p)
dev.off()
```

Plot factor coloured by gene expression
```{r}
genes <- c("Phlda2","Mesp1","Utf1","Dnmt3b")

for (i in genes) {
  
  p <- plot_factors(model,
    factors = 4,
    group_by = "group",
    color_by = i,
    rasterize = F,
    legend=F
  )
  # p <- p + scale_colour_gradientn(colours = terrain.colors(10))
  p <- p + theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks.y = element_blank(),
    strip.text = element_blank(),
    strip.background = element_blank()
  )
  # print(p)
  
  pdf(sprintf("%s/Factor4_%s.pdf",io$pdfdir,i), width=4, height=3, useDingbats = F)
  print(p)
  dev.off()
}
```
