---
title: "Gastrulation 10x: Robustness analysis of MOFA models"
output:
  BiocStyle::html_document: 
    toc: false
    fig_width: 10
    fig_height: 8
---
<!-- Load modules -->

```{r load_modules, echo=FALSE, include=FALSE}
library(MOFA2)
library(data.table)
library(purrr)
library(ggplot2)
library(pheatmap)
```


<!-- Define settings -->

```{r}
io <- list()
io$model.dir <- "/Users/ricard/data/gastrulation10x/mofa/hdf5"
io$outdir <- "/Users/ricard/data/gastrulation10x/mofa/pdf"

opts <- list()
opts$ntrials <- 3
```

<!-- Load precomputed models -->

```{r}
MOFAlist <- list()
for (i in 1:opts$ntrials) {
  outfile <- sprintf("%s/E6.5-E7.25_%d.hdf5",io$model.dir,i)
  MOFAlist[[i]] <- load_model(outfile)
}
```

<!-- Subset active factors -->

```{r}
# for (i in 1:opts$ntrials) {
#   r2 <- calculateVarianceExplained(MOFAlist[[i]])$R2PerFactor
#   factors <- r2[,"rna"]>0.005
#   MOFAlist[[i]] <- subsetFactors(MOFAlist[[i]], which(factors))
# }
```

<!-- Assess robustness of factors -->

```{r}
pdf(paste0(io$outdir,"/robustness.pdf"), height=7, width=8.5)
compare_factors(MOFAlist, show_rownames=F, show_colnames=F)
dev.off()
```

<!-- Select model with the highest ELBO -->

```{r}
compare_models(MOFAlist)
```
