---
title: "Find marker genes"
---

```{r load_modules, echo=FALSE, include=FALSE}
library(scater)
library(scran)
library(ggplot2)
library(ggpubr)
# library(RColorBrewer)
# library(umap)
```

```{r}
matrix.please <- function(x) {
  m<-as.matrix(x[,-1])
  rownames(m)<-x[[1]]
  m
}
```

# Define settings

Define I/O
```{r define_io, echo=FALSE}
# Load default settings
source("/Users/ricard/gastrulation10x/settings.R")

io$outdir <- paste0(io$basedir,"/results/marker_genes")
```

Define options
```{r}

```

# Load data

Load RNA expression data
```{r load_data, echo=FALSE}
sce <- readRDS(io$rna.sce)[,sample_metadata$cell]
sce$group <- sample_metadata$celltype3
```

Load gene metadata
```{r}
gene_metadata <- fread(io$gene_metadata)
# table(rownames(sce) %in% gene_metadata$ens_id)
```


# Find marker genes

```{r}
diff <- findMarkers(sce, sce$group, pval.type="all", test.type="t")
# saveRDS(diff, paste0(io$outdir,"/diff.rds"))
```

Calculate average gene expression and detection rate per group
```{r}
expr.dt <- unique(sce$group) %>% map(function(i) {
  dt <- logcounts(sce[,sce$group==i]) %>% as.matrix %>% as.data.table(keep.rownames = T) %>%
    melt(id.vars="rn") %>% setnames(c("ens_id","cell","value")) %>%
    .[,.(mean_expr=round(mean(value),3), detection_rate=round(mean(value>0),3)),by="ens_id"] %>%
    .[,group:=i]
  return(dt)
}) %>% rbindlist
```

Save
```{r}
to.save <- expr.dt %>%
  merge(gene_metadata[,c("symbol","ens_id")], all.x=T) %>%
  setnames("symbol","gene")

fwrite(to.save, paste0(io$outdir,"/avg_expr_per_celltype3_and_gene.txt.gz"), sep="\t")

rm(to.save)
```

Calculate logFC direction
```{r}
logfc_direction.dt <- names(diff) %>% map(function(i) {
  diff[[i]] %>% as.data.table(keep.rownames = T) %>% setnames("rn","ens_id") %>%
    .[,c("p.value","FDR"):=NULL] %>%
    melt(id.vars="ens_id") %>%
    .[,.(sign=c("-","+")[(mean(value>0)>0.5)+1]),by="ens_id"] %>%
    .[,group:=i]
}) %>% rbindlist
```

# Filter results

Options
```{r}
# This looks conservative, but it is not. t-test are very liberal
opts$fdr <- 1e-20

# Minimum fraction of cells that must express the gene (within each cell type)
opts$min.detection_rate <- 0.30

# If TRUE, keep only gene markers that are upregulated in the corresponding lineage when compared to all other lineages
# if FALSE, keep also marker genes that are downregulated in the corresponding lineage
opts$keep_only_upregulated <- TRUE
```

Do the filterng
```{r, message=F}
diff_filt <- list()
for (i in names(diff)) {
  
  diff_filt[[i]] <- diff[[i]] %>% 
    as.data.table(keep.rownames = T) %>%
    setnames("rn","ens_id") %>%
    .[,group:=i] %>%
    
    # Filter by FDR
    .[FDR<=opts$fdr] %>% .[,p.value:=NULL] %>%
    .[,c("group","ens_id","FDR")] %>%
  
    # Filter by mean expression
    merge(expr.dt,by=c("group","ens_id")) %>%
    .[detection_rate>=opts$min.detection_rate] %>%
  
    # Filter by logFC direction
    merge(logfc_direction.dt,by=c("group","ens_id"))
    if (isTRUE(opts$keep_only_upregulated)) {
      diff_filt[[i]] <- diff_filt[[i]][sign=="+"] %>% .[,sign:=NULL]
    }
  
    # Sort genes by FDR
    diff_filt[[i]] %>% setorder(FDR,mean_expr) 
}
diff_filt <- rbindlist(diff_filt) %>% 
  merge(gene_metadata[,c("symbol","ens_id")], all.x=T) %>%
  setnames("symbol","gene")
```


# Save

```{r}
fwrite(diff_filt, paste0(io$outdir,"/marker_genes.tsv.gz"), quote=F, sep="\t")
```
