

<!-- Factor 4  -->

Plot factor values
```{r}
p <- plot_factor(model,
  factors = c(4),
  group_by = "group", scale=T,
  color_by = sample_metadata_filt$lineage10x_2, 
  add_violin = T, color_violin = T,
  dodge=T, dot_size=1, legend = F, rasterize = F
)
p <- p + scale_color_manual(values=opts$colors) + scale_fill_manual(values=opts$colors)
p <- p + theme(
  strip.text = element_text(size=rel(1.3), color="black"),
  strip.background = element_blank(),
)
pdf(paste0(io$pdfdir,"/Factor4_values.pdf"), width=opts$factors.width, height=opts$factors.height, useDingbats = F)
print(p)
dev.off()
```

Plot weights
```{r}
p <- plot_weights(model,
  view = "RNA",
  factor = 1,
  nfeatures = 5,
  text_size = 5,
  scale=T, abs=F
)

# p <- plot_top_weights(model, 
#   view = "RNA", 
#   factor = 4, 
#   nfeatures = 10,
#   scale=T, abs=T, 
# )

pdf(paste0(io$pdfdir,"/Factor4_loadings.pdf"), width=3.5, height=3, useDingbats = F)
print(p)
dev.off()
```

Plot factor coloured by gene expression
```{r}
genes <- c("Phlda2","Mesp1","Utf1","Dnmt3b")

for (i in genes) {
  
  p <- plot_factor(model,
    factors = 4,
    group_by = "group",
    color_by = i,
    rasterize = F,
    legend=F
  )
  
  p <- p + scale_colour_gradientn(colours = terrain.colors(10))
  
  p <- p + theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks.y = element_blank(),
    strip.text = element_blank(),
    strip.background = element_blank()
  )
  # print(p)
  
  pdf(sprintf("%s/Factor4_%s.pdf",io$pdfdir,i), width=3.8, height=2, useDingbats = F)
  print(p)
  dev.off()
}
```




